version: "3"

services:
  telegram-bot:
    build: .
    image: xcontest-rss-monitor:latest
    volumes:
      - .:/app
      - ./state:/state
    environment:
      APP_XCONTEST_FEED_URL: FILLME
      APP_TELEGRAM_BOT_TOKEN: FILLME
